### ISSUE TITLE
DROP_WARN logging at debug level

### ISSUE THREAD

**Issue by phlope** [aiven/aiven-kafka-connect-transforms#10]
We configured drop.warn but aren't seeing any messages coming through as tombstones,

Should this be set as LOGGER.debug in the below:

https://github.com/aiven/aiven-kafka-connect-transforms/blob/9e819a71ae238b77c5f62f8eb8ea6e50f726d2a9/src/main/java/io/aiven/kafka/connect/transforms/TombstoneHandler.java#L71

**Comment by ivanyu** [comment]
Hi,

Thank you for reporting. It should be `LOGGER.warn`, of course. We'll fix it.

**Comment by phlope** [comment]
Awesome, thanks!
