### ISSUE TITLE
Hash SMT replaces the whole message

### ISSUE THREAD

**Issue by nick-zh** [aiven/aiven-kafka-connect-transforms#15]
I am adding this here too, so when i tested this with the following connector configuration:
```
    "transforms.HashEmail.type": "io.aiven.kafka.connect.transforms.Hash$Value",
    "transforms.HashEmail.field.name": "email",
    "transforms.HashEmail.function": "md5",
    "transforms.HashEmail.skip.missing.or.null": "true"
```
What i end up with is just the hashed value, it seems the whole message is replaced instead of just the email field, i end up with something like this:
```
"5ABCdefTu+abc123456789=="
```
maybe @brbrown25, before i dig into this, you already know maybe where to fix this.

**Comment by brbrown25** [comment]
@nick-zh I can take a look at this, I think I might know where it's happening. will do that this afternoon/evening.

**Comment by ivanyu** [comment]
I'll also have a look soon
This test should cover it:
https://github.com/aiven/aiven-kafka-connect-transforms/blob/master/src/test/java/io/aiven/kafka/connect/transforms/HashTest.java#L193

**Comment by brbrown25** [comment]
@ivanyu and @nick-zh I see the issue and can have a fix this evening. It is indeed hashing the entire value and setting it rather than just on the configured field

**Comment by nick-zh** [comment]
@brbrown25 thx for the quick feedback, really appreciate it :v:

**Comment by brbrown25** [comment]
pr is opened that should address this issue!

**Comment by nick-zh** [comment]
Big thanks to @brbrown25 and @ivanyu for reacting so quickly :bow:
