### ISSUE TITLE
[Question] How to extend Hash for multiple field and build failure

### ISSUE THREAD

**Issue by scheung38** [aiven/aiven-kafka-connect-transforms#19]
Example is showing use of field value email:

transforms=HashEmail
transforms.HashEmail.type=io.aiven.kafka.connect.transforms.Hash$Value
transforms.HashEmail.field.name=email
transforms.HashEmail.function=sha1

Extending to hash from multiple field values would be?
transforms=HashEmail
transforms.HashEmail.type=io.aiven.kafka.connect.transforms.Hash$Value
transforms.HashEmail.field.name=email, username, address <---- ?
transforms.HashEmail.function=sha1

EDIT: BUILD SUCCESSFUL Now

But not sure how to use it?

**Comment by brbrown25** [comment]
@scheung38 I'll need to look as I believe the current functionality does not work like that, it will only do a single field. You might be able to either 1) add multiple transforms or 2) maybe it should support multiple fields. Not sure what the maintainers think. I also have a KIP to fold this into kafka proper so I'll ask the mailing list.

**Comment by ivanyu** [comment]
@scheung38 we currently don't have a plan to add hashing for multiple fields.
The primary reason for avoiding this is that it would make the transformation doing a bit too much. Potentially, this could be a two transformations in chain: one for field concatenation and one for hashing.

**Comment by ivanyu** [comment]
UPD: I assume that I misunderstood your question and you don't actually need multiple field values to be concatenated before hashing, but be hashed separately.
If I'm right, all you need is to setup several hash transformations for each field separately.

**Comment by scheung38** [comment]
@ivanyu specifically it is to concat say dynamic combinations with ~ in between them and then hash

op_id, business_id, month, year, age, gender, address

hash(year, month, business_id)

and then

later on

hash(address, year, month, business_id)

**Comment by brbrown25** [comment]
@scheung38 you'll need multiple transforms to achieve that, first the concatenation, then the hashing. The concatenation would need to be a custom transform you create.

**Comment by scheung38** [comment]
Hi @brbrown25 but as I mentioned earlier, multiple transforms might not give the same single hash of concat fields?

**Comment by brbrown25** [comment]
> Hi @brbrown25 but as I mentioned earlier, multiple transforms might not give the same single hash of concat fields?
if you have a schema with fields `op_id, business_id, month, year, age, gender, address` and you want to concat `year, month, business_id` the first transform would concat those into a new field, lets call it `combined` so then your schema would be `op_id, business_id, month, year, age, gender, address, combined.` Then you would have the hash transform run on the field `combined` so your schema would remain as `op_id, business_id, month, year, age, gender, address, combined` but `combined` would go from being a concatenated string to being a hashed value. you could then even add a drop transformer to remove the fields that were combined and hashed. Does that make sense?

**Comment by scheung38** [comment]
Yes I am aware, but my question was whether the hashing mechanism for chained hashing would give the anwer resultant hash as a singular concatenate hash

**Comment by brbrown25** [comment]
Ah so you mean hash(field1), hash(field2), hash(field3) as three transforms and then a fourth transform that concatenates those?

**Comment by brbrown25** [comment]
> So it would be CSV -> topic_ingested -> topic_ingested_with_concat -> topic_ingested_with_concat_hashed 
> 
> 
> 
> or this is done all in one go:
> 
> 
> 
> CSV -> UDF -> topic_ingested_with_concat_hashed

I'll put together an example config shortly for what this would look like

**Comment by brbrown25** [comment]
@scheung38 here would be an example configuration
```
"transforms":"HashYear,HashMonth,HashBusinessId,ConcatFields,ReplaceField",
"transforms.HashYear.type":"io.aiven.kafka.connect.transforms.Hash$Value",
"transforms.HashYear.field.name":"year",
"transforms.HashYear.function":"sha1",
"transforms.HashMonth.type":"io.aiven.kafka.connect.transforms.Hash$Value",
"transforms.HashMonth.field.name":"month",
"transforms.HashMonth.function":"sha1",
"transforms.HashBusinessId.type":"io.aiven.kafka.connect.transforms.Hash$Value",
"transforms.HashBusinessId.field.name":"business_id",
"transforms.HashBusinessId.function":"sha1",
"transforms.ConcatFields.type": "<your-package-name>.ConcatFields",
"transforms.ConcatFields.fields": "year, month, business_id",
"transforms.ReplaceField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value",
"transforms.ReplaceField.blacklist": "year, month, business_id"
```

**Comment by scheung38** [comment]
No, to be specific hash(concat(field1 ~ field2 ~ field 3)). 

So field1 concat tilda concat field2 concat tilda concat field3, and then the whole thing hashed

**Comment by brbrown25** [comment]
I mean something like this would do that...this would
Combine those fields with a tilde and then hash that and then drop those original fields. You'd need to write a transformer for the concatenation. But the hash should be stable given the fields you supply as input. 
"transforms":"ConcatFields,HashCombined, ReplaceField",
"transforms.HashCombined.type":"io.aiven.kafka.connect.transforms.Hash$Value",
"transforms. HashCombined.field.name":"combined",
"transforms. HashCombined.function":"sha1",
"transforms.ConcatFields.type": "<your-package-name>.ConcatFields",
"transforms.ConcatFields.fields": "year, month, business_id",
"transforms.ConcatFields.delimiter": "~",
"transforms.ReplaceField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value",
"transforms.ReplaceField.blacklist": "year, month, business_id"

**Comment by scheung38** [comment]
BTW are there instructions to try out this connector as I have only Confluent install connectors there. Here I need to gradle build but not sure how to integrate with other connectors from hub

**Comment by brbrown25** [comment]
> BTW are there instructions to try out this connector as I have only Confluent install connectors there. Here I need to gradle build but not sure how to integrate with other connectors from hub


You can get a release from here https://github.com/aiven/aiven-kafka-connect-transforms/releases/tag/v1.0.0

And then follow
https://docs.confluent.io/current/connect/managing/community.html 
For manually installing a connector not available through confluent. This would be the same flow needed for you to install a custom concat connector your create. @ivanyu do you think a concatenation transformer would be a nice addition to this library? If so I can create an issue and put together a pr.

**Comment by ivanyu** [comment]
@brbrown25 yes, thank you, the concat transformer would be a good addition. Could you please put some example configuration(s) to the ticket so we could discuss how it looks like from the user experience point of view?

**Comment by brbrown25** [comment]
> Could you please put some example configuration(s) to the ticket so we could discuss how it looks like from the user experience point of view?
@ivanyu I was thinking something like the following
```
field.names //fields to concat
field.name //field to place the concatenated string into
delimiter //the delimiter to be used
field.replace.missing //a value that should be used when no value is present for a given field
```
I'm not super sold on the name of those first two config keys though so would love your thoughts. Regardless, in practice you would get something like this. 
```
"field.names" = "test,foo,bar"
"field.name" = "combined"
"delimiter" = "-"
"field.replace.missing" = "*"
```
for message
```
{
  "test": "something cool",
  "foo": true,
  "bar": 1,
  "timestamp": 1600864778131
}
```
it would transform to
```
{
  "test": "something cool",
  "foo": true,
  "bar": 1,
  "combined": "something cool-true-1",
  "timestamp": 1600864778131
}
```

and in the case where a field is missing
```
{
  "test": "something cool",
  "foo": true,
  "timestamp": 1600864778131
}
```
it would create
```
{
  "test": "something cool",
  "foo": true,
  "combined": "something cool-true-*",
  "timestamp": 1600864778131
}
```

**Comment by scheung38** [comment]
> I mean something like this would do that...this would
> Combine those fields with a tilde and then hash that and then drop those original fields. You'd need to write a transformer for the concatenation. But the hash should be stable given the fields you supply as input.
> "transforms":"ConcatFields,HashCombined, ReplaceField",
> "transforms.HashCombined.type":"io.aiven.kafka.connect.transforms.Hash$Value",
> "transforms. HashCombined.field.name":"combined",
> "transforms. HashCombined.function":"sha1",
> "transforms.ConcatFields.type": ".ConcatFields",
> "transforms.ConcatFields.fields": "year, month, business_id",
> "transforms.ConcatFields.delimiter": "~",
> "transforms.ReplaceField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value",
> "transforms.ReplaceField.blacklist": "year, month, business_id"
> 
> I'm not quite clear about how hash output would change. For a given input you hash it should always create the same output
