### ISSUE TITLE
Create a github Action for pull requests

### ISSUE THREAD

**Issue by brbrown25** [aiven/aiven-kafka-connect-transforms#28]
The build times in travis ci take a long time, it would be awesome if this was done inside of a github action, maybe even making it so merges to master automatically problished a snapshot version? If there is interesting, I'd love to take a crack at it.

**Comment by ivanyu** [comment]
Will be done in https://github.com/aiven/aiven-kafka-connect-transforms/pull/29

**Comment by ivanyu** [comment]
Travis is shutting down soon
